name: Gemoe

on:
  push:
    paths:
      - "Dockerfile"
      - "requirements.txt"
  
  schedule:
    - cron: "0 0 * * 0"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:      
      - name: Login to Docker.io
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@master
        with:
          tags: |
            gemoe
          images: |
            arakurumi/bot
          labels: |
            org.opencontainers.image.authors=Kurumi <kqruumi@gmail.com>
            org.opencontainers.image.description=Docker Images for GeMoe
            org.opencontainers.image.licenses=Unlicense
            org.opencontainers.image.source=https://github.com/arakurumi/docker-bot
            org.opencontainers.image.title=Docker-Bot
            org.opencontainers.image.url=https://github.com/arakurumi/docker-bot
            org.opencontainers.image.version=ubuntu
          annotations: |
            org.opencontainers.image.authors=Kurumi <kqruumi@gmail.com>
            org.opencontainers.image.description=Docker Images for GeMoe
            org.opencontainers.image.licenses=Unlicense
            org.opencontainers.image.source=https://github.com/arakurumi/docker-bot
            org.opencontainers.image.title=Docker-Bot
            org.opencontainers.image.url=https://github.com/arakurumi/docker-bot
            org.opencontainers.image.version=ubuntu

      - name: Build and Push to Docker.io
        uses: docker/build-push-action@master
        with:
          push: true
          context: "{{defaultContext}}:Gemoe"
          no-cache: true
          provenance: false
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
