name: TERABOX

on:
  push:
    paths:
      - "Dockerfile"
      - "requirements.txt"
  
  schedule:
    - cron: "0 0 * * 0"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: labani/terabox
          tags: |
            mltb-latest
          labels: |
            org.opencontainers.image.authors=Kurumi <dolabani46@gmail.com>
            org.opencontainers.image.description=Docker Images for TERABOX
            org.opencontainers.image.licenses=Unlicense
            org.opencontainers.image.source=https://github.com/zxllbni/Docker-Bot
            org.opencontainers.image.title=Docker-Bot
            org.opencontainers.image.version=latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
